---
- name: Copy ISDbg.exe
  win_copy:
    src: "{{ ISProductFolder }}/System/ISDbg.exe"
    dest: "{{ ISDbgFolder }}/ISDbg.exe"

- name: Copy SciLexer.dll
  win_copy:
    src: "{{ ISProductFolder }}/System/SciLexer.dll"
    dest: "{{ ISDbgFolder }}/SciLexer.dll"
  when: ISVersion >= "2012"

- name: Copy ISDbg.chm (English)
  win_copy:
    src: "{{ ISProductFolder }}/Program/0409/ISdbg.chm"
    dest: "{{ ISDbgFolder }}/ISdbg.chm"
  failed_when: no

- name: Copy ISDbg.chm (Japanese)
  win_copy:
    src: "{{ ISProductFolder }}/Program/0411/ISdbg.chm"
    dest: "{{ ISDbgFolder }}/ISdbg.chm"
  failed_when: no
